[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test'
cache_path = 'cache/foundry'
optimizer = true
optimizer_runs = 200
match-path = "test/**/*.t.sol"
match-contract = "Test$"
# deny_warnings = true

libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
berachain = "${BERA_RPC_URL}"
bsc = "https://binance.llamarpc.com"
polygon = "https://polygon.llamarpc.com"
ftm = "https://fantom-rpc.publicnode.com"
optimism = "https://mainnet.optimism.io"
moonriver = "https://rpc.api.moonriver.moonbeam.network"
kava = "https://evm.kava-rpc.com"
base = "https://base.llamarpc.com"
linea = "https://1rpc.io/linea"
blast = "https://rpc.blast.io"